(()=>{'use strict';
const E=window.KSEngine,$=x=>document.getElementById(x),all=q=>[...document.querySelectorAll(q)];
const N=new Intl.NumberFormat('ko-KR',{maximumFractionDigits:0});
const names={fixed10:'고정 10%',fixed20:'고정 20%',quarter:'쿼터 켈리 · 상한 적용',half:'하프 켈리 · 상한 적용',full:'풀 켈리 · 상한 적용',buyhold:'100% 단순 보유'};
const colors={fixed10:'#9db5c8',fixed20:'#89d5b0',quarter:'#b5a0d5',half:'#d2f791',full:'#e8bc77',buyhold:'#fa9d95'};
const pc=x=>x===null||!Number.isFinite(x)?'추정 보류':(x*100).toFixed(2)+'%';
const pct=x=>(x>=0?'+':'')+(x*100).toFixed(2)+'%';
const won=x=>N.format(Math.round(x))+'원';const brief=x=>x>=1e8?(x/1e8).toFixed(2)+'억 원':x>=1e4?N.format(x/1e4)+'만 원':won(x);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let source=window.KELLY_PRICES||null,stocks=source?.stocks||[],result=null,resultStock=null,replay=null,tab='setup',includeHold=false,toastTimer;
const notes={trend:'전일 종가 > 20일 평균, 20일 평균 > 60일 평균이면 다음 시가 매수. 보유 중 중복 매수하지 않습니다.',breakout:'전일 종가가 그 이전 20일 고가의 최댓값을 넘으면 다음 시가 매수합니다.',pullback:'전일 종가가 해당일 20일 종가 평균보다 5% 이상 낮으면 다음 시가 매수합니다. 저가 매수의 우위가 있다는 가정은 하지 않습니다.'};
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3400);}
function current(){return stocks[Number($('stock').value)];}
function switchTab(t){tab=t;all('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===t);b.setAttribute('aria-current',b.dataset.tab===t?'page':'false');});['setup','results','replay','data'].forEach(n=>$(n+'Page').hidden=n!==t);window.scrollTo(0,0);if(t==='replay'&&!replay&&current())startReplay();if(t==='results'&&result)renderResults();}
function fillStocks(){const prev=$('stock').value;$('stock').innerHTML='';for(let i=0;i<stocks.length;i++){const o=document.createElement('option');o.value=i;o.textContent=stocks[i].name+' · '+stocks[i].code;$('stock').append(o);}if(!stocks.length){$('stock').innerHTML='<option value="">자료 없음 · CSV를 불러오세요</option>';$('runBtn').disabled=true;$('dataStatus').textContent='가격 파일을 읽지 못했습니다. 데이터·원리에서 CSV를 불러올 수 있습니다.';}else{$('runBtn').disabled=false;$('stock').value=prev&&stocks[Number(prev)]?prev:'0';selectStock();}}
function selectStock(){const s=current();if(!s)return;const b=s.rows;$('from').value=b[0][0];$('to').value=b[b.length-1][0];$('dataStatus').textContent=(s.local?'내 CSV':'내장 과거 일봉')+' · '+b[0][0]+' ~ '+b[b.length-1][0]+' · '+N.format(b.length)+'개 · 실시간 아님';}
function config(){if(!$('designForm').checkValidity()){$('designForm').reportValidity();throw Error('입력 범위를 확인하세요.');}const v=id=>Number($(id).value);const c={capital:v('capital'),rule:$('rule').value,from:$('from').value,to:$('to').value,tp:v('tp')/100,sl:v('sl')/100,hold:v('hold'),cap:v('cap')/100,split:v('split'),min:v('minimum'),fee:v('fee')/100,tax:v('tax')/100,slip:v('slip')/100};if(c.from>=c.to)throw Error('종료일이 시작일보다 뒤여야 합니다.');if(Object.values(c).some(x=>typeof x==='number'&&!Number.isFinite(x)))throw Error('유효한 숫자를 입력하세요.');return c;}
function sourceInfo(){if(!source){$('sourceInfo').textContent='내장 가격 파일을 읽지 못했습니다. 가상 가격으로 대체하지 않습니다.';return;}$('sourceInfo').innerHTML='<p>'+esc(source.provider)+' · 저장 시점 '+esc(source.fetched_at.slice(0,10))+'</p>'+source.stocks.map(s=>'<p><b>'+esc(s.name)+' ('+esc(s.code)+')</b><br>'+esc(s.first_date)+' ~ '+esc(s.last_date)+' / '+N.format(s.row_count)+'개 일봉</p>').join('')+'<p>'+esc(source.adjustment)+'</p><p>현재 페이지는 저장본을 읽을 뿐 주가를 자동 갱신하지 않습니다. 오류 행·중복 날짜·가격 범위는 검사했지만 별도 공급자와 교차 검증한 가격은 아닙니다.</p>';}
function chart(el,series,dates,unit='equity'){
 const small=innerWidth<800,W=small?400:800,H=small?258:300,L=small?48:66,R=16,T=15,B=34,iw=W-L-R,ih=H-T-B;el.setAttribute('viewBox',`0 0 ${W} ${H}`);
 const vals=series.flatMap(s=>s.values).filter(Number.isFinite);if(!vals.length){el.innerHTML='';return;}let lo=Math.min(...vals),hi=Math.max(...vals),gap=Math.max(hi-lo,hi*.01,1);lo=Math.max(0,lo-gap*.1);hi+=gap*.1;const len=Math.max(...series.map(s=>s.values.length)),x=i=>L+iw*i/Math.max(1,len-1),y=v=>T+(hi-v)/(hi-lo)*ih;let out='<title>'+ (unit==='price'?'진행된 과거 종가':'검증 구간 자금 추이')+'</title>';
 for(let j=0;j<4;j++){const v=lo+(hi-lo)*j/3,Y=y(v);const label=unit==='price'?(v>=10000?(v/10000).toFixed(1)+'만':N.format(v)):N.format(v);out+=`<line x1="${L}" y1="${Y}" x2="${W-R}" y2="${Y}" stroke="#354239"/><text x="${L-7}" y="${Y+4}" fill="#a9b8ad" text-anchor="end" font-size="10">${esc(label)}</text>`;}
 if(unit==='equity'&&lo<=100&&hi>=100)out+=`<line x1="${L}" y1="${y(100)}" x2="${W-R}" y2="${y(100)}" stroke="#aab599" stroke-dasharray="4 5"/>`;
 for(const s of series){const d=s.values.map((v,i)=>(i?'L':'M')+x(i).toFixed(2)+','+y(v).toFixed(2)).join(' ');out+=`<path d="${d}" stroke="${s.color}" fill="none" stroke-width="${s.highlight?2.8:1.35}" opacity="${s.highlight?1:.75}"/>`;}
 if(dates.length)out+=`<text x="${L}" y="${H-8}" fill="#a9b8ad" font-size="10">${esc(dates[0])}</text><text x="${W-R}" y="${H-8}" fill="#a9b8ad" font-size="10" text-anchor="end">${esc(dates[dates.length-1])}</text>`;
 el.innerHTML=out;
}
function line(label,value){return '<div class="fitline"><span>'+esc(label)+'</span><b>'+esc(value)+'</b></div>';}
function selected(){return result.variants.find(s=>s.kind===$('focusStrategy').value);}
function renderResults(){const r=result,c=r.c,k=$('focusStrategy').value,s=selected();$('emptyResults').hidden=true;$('resultContent').hidden=false;
 $('resultMeta').textContent=resultStock.name+' · 검증 '+r.b[r.split][0]+' ~ '+r.b[r.b.length-1][0]+' · 초기 '+Math.round(c.split*100)+'% 추정, 이후 '+Math.round((1-c.split)*100)+'% 검증 · 종료 거래만 순차 반영';
 $('metrics').innerHTML=[['최종 가상 자금',brief(s.final),''],['수익률',pct(s.ret),s.ret>=0?'up':'down'],['일별 최대 낙폭',pc(s.dd),'down']].map(x=>`<div class="metric"><span>${x[0]}</span><b class="${x[2]}">${x[1]}</b></div>`).join('');
 const list=r.variants.filter(v=>includeHold||v.kind!=='buyhold');if(k==='buyhold'&&!includeHold)list.push(s);list.sort((a,b)=>(a.kind===k?1:0)-(b.kind===k?1:0));
 chart($('equityChart'),list.map(v=>({values:v.curve.map(x=>100*x/c.capital),color:colors[v.kind],highlight:v.kind===k})),[r.b[r.split][0],r.b[r.b.length-1][0]]);
 $('legend').innerHTML=list.map(v=>'<span><i style="background:'+colors[v.kind]+'"></i>'+esc(names[v.kind])+'</span>').join('');
 const f=r.initialFit;$('fitInfo').innerHTML=line('초기 완료 규칙 거래',f.n+'건')+line('승률 (표본값)',f.p===null?'거래 없음':pc(f.p))+line('평균 이익 / 평균 손실',pc(f.win)+' / '+pc(f.loss))+line('평균 순수익률',pct(f.avg))+line('초기 풀 켈리 (상한 전)',pc(r.initialKelly));
 $('fitWarn').textContent=(r.initialKelly===null?'초기 표본이 최소 '+c.min+'건보다 적어 켈리 전략은 우선 관망합니다. ':r.initialKelly===0?'초기 표본에서 비용 차감 우위가 확인되지 않아 켈리는 0%로 시작합니다. ':'과거 표본의 추정치이며 드문 대폭락을 보장 범위에 넣지 않습니다. ')+ '쿼터·하프·풀 모두 상한 '+pc(c.cap)+'를 적용하므로 서로 같아질 수 있습니다.';
 const lk=r.latestKelly;$('latestInfo').innerHTML=line('누적 완료 규칙 표본',r.latestFit.n+'건')+line('풀 켈리 추정 (상한 전)',pc(lk))+line('쿼터 · 상한 적용',lk===null?'추정 보류':pc(Math.min(c.cap,lk*.25)))+line('하프 · 상한 적용',lk===null?'추정 보류':pc(Math.min(c.cap,lk*.5)))+line('풀 · 상한 적용',lk===null?'추정 보류':pc(Math.min(c.cap,lk)));
 $('scoreBody').innerHTML=r.variants.map(v=>`<tr class="${v.kind===k?'selected-row':''}"><td><button data-focus="${v.kind}">${names[v.kind]}</button></td><td>${won(v.final)}</td><td class="${v.ret>=0?'up':'down'}">${pct(v.ret)}</td><td>${pc(v.dd)}</td><td>${v.count}</td></tr>`).join('');
 $('ledgerInfo').textContent=names[k]+' · '+s.count+'회 체결 / '+s.ledger.length+'개 신호 · 동일 일봉 익절·손절 접촉 '+s.ledger.filter(x=>x.ambiguous).length+'건. 날짜별 수익은 반올림 표시합니다.';
 $('ledgerBody').innerHTML=s.ledger.length?s.ledger.map(t=>`<tr><td>${r.b[t.entry][0]} → ${r.b[t.exit][0]}</td><td>${pc(t.f)}</td><td>${t.q}</td><td class="${t.pnl>=0?'up':'down'}">${won(t.pnl)}</td><td>${t.n||'—'}</td><td>${t.skipped?'관망 / 1주 매수금 부족':esc(t.why)}</td></tr>`).join(''):'<tr><td colspan="6">이 규칙에 맞는 진입이 없습니다. 기간·규칙을 확인하세요.</td></tr>';
}
function download(name,text){const u=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),20000);toast('파일 저장을 요청했습니다. 브라우저 다운로드를 확인하세요.');}
function exportTrades(){if(!result)return;const s=selected(),r=result;const head=['종목','방식','진입일','청산일','매수가_체결오차포함','매도가_체결오차포함','비중','주수','순손익','종료자금','과거표본수','풀켈리추정','청산이유','수수료_각각','매도추가비용','체결오차_각각'];const rows=s.ledger.map(t=>[resultStock.name,names[s.kind],r.b[t.entry][0],r.b[t.exit][0],t.in,t.out,t.f,t.q,t.pnl,t.after,t.n??'',t.k??'',t.skipped?'관망 / 1주 부족':t.why,r.c.fee,r.c.tax,r.c.slip]);download('kelly_stock_trades.csv',[head,...rows].map(a=>a.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(',')).join('\r\n'));}
function startReplay(){try{const s=current(),c=config();if(!s)throw Error('종목 자료를 먼저 불러오세요.');const b=E.validate(s.rows).filter(x=>x[0]>=c.from&&x[0]<=c.to);if(b.length<240)throw Error('훈련에 최소 240일이 필요합니다.');const i=Math.floor(b.length*c.split)-1;replay={b,c,name:s.name,i,cash:c.capital,q:0,entry:0,entryDay:0,debit:0,peak:c.capital,dd:0,ledger:[],event:'다음 날부터 검증 구간입니다. 매수 또는 관망을 선택하세요.'};renderReplay();}catch(e){toast(e.message);}}
function closeReplay(px,why){const p=replay,net=p.q*px*(1-p.c.fee-p.c.tax),pnl=net-p.debit;p.cash+=net;p.ledger.push({date:p.b[p.i][0],pnl,why});p.q=0;p.debit=0;p.event=why+' · 순손익 '+won(pnl);}
function stepReplay(action){const p=replay;if(!p||p.i>=p.b.length-1)return;const f=Number($('replayBet').value)/100;if(!Number.isFinite(f)||f<0||f>1){toast('매수 비중은 0~100%입니다.');return;}if(action==='buy'&&p.q>0)return;if(action==='sell'&&!p.q)return;p.i++;const bar=p.b[p.i];p.event=bar[0]+' · 하루 진행';let bought=false;
 if(action==='sell'&&bar[5]>0)closeReplay(bar[1]*(1-p.c.slip),'다음 시가 매도');
 if(action==='buy'&&bar[5]>0){const px=bar[1]*(1+p.c.slip),q=Math.floor(p.cash*f/(px*(1+p.c.fee)));if(q>0){p.q=q;p.entry=px;p.entryDay=p.i;p.debit=q*px*(1+p.c.fee);p.cash-=p.debit;bought=true;p.event=q+'주 매수 · 체결가 '+won(px);}else p.event='비중 0% 또는 1주 매수금 부족으로 관망했습니다.';}
 if(p.q){const e=E.exitAt(bar,p.entry,p.i-p.entryDay+1,p.c,bought);if(e)closeReplay(e.px,e.why);}
 if(p.i===p.b.length-1&&p.q)closeReplay(bar[4]*(1-p.c.slip),'훈련 종료·종가 청산');
 const value=p.cash+p.q*bar[4];p.peak=Math.max(p.peak,value);p.dd=Math.max(p.dd,1-value/p.peak);renderReplay();}
function renderReplay(){if(!replay)return;const p=replay,b=p.b[p.i],value=p.cash+p.q*b[4],done=p.i>=p.b.length-1;$('replayTitle').textContent=p.name+' · '+b[0];$('replayBalance').textContent=won(value);$('replayStatus').textContent='수익률 '+pct(value/p.c.capital-1)+' · 종가 '+won(b[4])+' · 보유 '+p.q+'주 · 최대 낙폭 '+pc(p.dd);const visible=p.b.slice(Math.max(0,p.i-89),p.i+1);chart($('priceChart'),[{values:visible.map(x=>x[4]),color:'#d2f791',highlight:true}],visible.map(x=>x[0]),'price');$('buyReplay').disabled=done||p.q>0;$('sellReplay').disabled=done||p.q===0;$('nextReplay').disabled=done;$('replayEvent').textContent=p.event+(done?' / 준비된 기간의 훈련을 마쳤습니다.':'');}
$('designForm').addEventListener('submit',async e=>{e.preventDefault();$('formError').hidden=true;$('runBtn').disabled=true;$('runBtn').textContent='과거 거래와 비중 계산 중…';await new Promise(r=>setTimeout(r,40));try{const s=current();if(!s)throw Error('먼저 주가 자료를 선택하세요.');const c=config();result=E.run(s.rows,c);resultStock={name:s.name,code:s.code};renderResults();switchTab('results');}catch(err){$('formError').textContent=err.message;$('formError').hidden=false;}finally{$('runBtn').disabled=!stocks.length;$('runBtn').textContent='과거 주가로 검증하기 ↗';}});
all('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$('stock').addEventListener('change',selectStock);$('rule').addEventListener('change',()=>$('ruleNote').textContent=notes[$('rule').value]);$('focusStrategy').addEventListener('change',renderResults);$('scoreBody').addEventListener('click',e=>{const b=e.target.closest('[data-focus]');if(b){$('focusStrategy').value=b.dataset.focus;renderResults();}});$('exportBtn').addEventListener('click',exportTrades);$('toggleHold').addEventListener('click',()=>{includeHold=!includeHold;$('toggleHold').textContent=includeHold?'차트에서 100% 단순 보유 숨기기':'차트에 100% 단순 보유 추가';renderResults();});
$('restartReplay').addEventListener('click',startReplay);$('buyReplay').addEventListener('click',()=>stepReplay('buy'));$('sellReplay').addEventListener('click',()=>stepReplay('sell'));$('nextReplay').addEventListener('click',()=>stepReplay('next'));
$('csvInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;$('csvMessage').hidden=false;try{if(f.size>3*1024*1024)throw Error('CSV는 3MB 이하만 지원합니다.');const buffer=await f.arrayBuffer();let text=new TextDecoder('utf-8').decode(buffer);if(text.includes('\uFFFD'))text=new TextDecoder('euc-kr').decode(buffer);const rows=E.csv(text);stocks.push({name:$('csvName').value.trim()||f.name,code:'CSV',rows,local:true});fillStocks();$('stock').value=String(stocks.length-1);selectStock();$('csvMessage').textContent=rows.length+'개 일봉을 읽었습니다. 검증 설계에서 내 CSV를 선택했습니다.';toast('CSV를 읽었습니다. 검증 설계로 이동하세요.');}catch(err){$('csvMessage').textContent=err.message;}e.target.value='';});
$('sampleCSV').addEventListener('click',()=>download('csv_format_example_not_market_data.csv','Date,Open,High,Low,Close,Volume\r\n2025-01-02,10000,10200,9900,10100,100000\r\n2025-01-03,10100,10300,10000,10200,120000\r\n'));
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(result&&tab==='results')renderResults();if(replay&&tab==='replay')renderReplay();},150);});
fillStocks();sourceInfo();$('ruleNote').textContent=notes[$('rule').value];
window.KellyStockLab=Object.freeze({version:'0.1',snapshot:()=>({tab,stocks:stocks.map(s=>({name:s.name,rows:s.rows.length})),result:result?{name:resultStock.name,training:result.training.length,testing:result.testing.length,initialKelly:result.initialKelly,variants:result.variants.map(v=>({kind:v.kind,final:v.final,dd:v.dd,count:v.count}))}:null,replay:replay?{date:replay.b[replay.i][0],cash:replay.cash,q:replay.q,dd:replay.dd,events:replay.ledger.length}:null})});
})();
